#pragma once

#if defined(OPENXJ380CONFIG_CLEAR_RUN)
#define OPENXJ380_GUI_DISABLED 1
#define OPENXJ380_CONSOLE_DISABLED 1
#define OPENXJ380_INPUT_OUTPUT_DISABLED 1
#else
#define OPENXJ380_GUI_DISABLED 0
#define OPENXJ380_CONSOLE_DISABLED 0
#define OPENXJ380_INPUT_OUTPUT_DISABLED 0
#endif
