#pragma once

/*
 * Browser-only Mbed TLS configuration for XJ380 userland.
 */

#undef MBEDTLS_HAVE_ASM
#undef MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE
#undef MBEDTLS_HAVE_SSE2

#define MBEDTLS_NO_UDBL_DIVISION

#undef MBEDTLS_AESNI_C
#undef MBEDTLS_AESCE_C
#undef MBEDTLS_PADLOCK_C

#undef MBEDTLS_TIMING_C
#undef MBEDTLS_THREADING_C
#undef MBEDTLS_THREADING_PTHREAD
#undef MBEDTLS_THREADING_ALT
#undef MBEDTLS_NET_C
#undef MBEDTLS_FS_IO

#undef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_PSA_CRYPTO_CLIENT
#undef MBEDTLS_PSA_CRYPTO_CONFIG
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_USE_PSA_CRYPTO
#undef MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG

#undef MBEDTLS_SSL_PROTO_TLS1_3
#undef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#undef MBEDTLS_SSL_SRV_C

#undef MBEDTLS_DEBUG_C
#undef MBEDTLS_LMS_C
#undef MBEDTLS_LMOTS_C

#define MBEDTLS_NO_PLATFORM_ENTROPY

#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_CALLOC_MACRO calloc
#define MBEDTLS_PLATFORM_FREE_MACRO free
